### ISSUE TITLE
draw: Improve arrows

### ISSUE THREAD

**Issue by johannes-wolf** [johannes-wolf/cetz#162]
- Try calculating the miter (depending on miter style and width) 
- Add options for out/insetting arrow heads

Example of Tikz arrows:
![grafik](https://github.com/johannes-wolf/typst-canvas/assets/519002/3e65ae12-a030-4e42-97ce-0c821d338b38)

Example in CeTZ:
![grafik](https://github.com/johannes-wolf/typst-canvas/assets/519002/c12452f3-22b6-4b32-92d9-4f022b6425c9)

**Comment by Andrew15-5** [comment]
I will link the #161 discussion, just in case.
