### ISSUE TITLE
draw: a way to draw a circular arc from its center and angle radiuses

### ISSUE THREAD

**Issue by SekoiaTree** [johannes-wolf/cetz#202]
Currently, `arc` takes a start position, an angle, and a radius. This makes it annoying if you want to do, for example, concentric circular arcs, since you need to calculate the start position every time.

This could be a styling on `circle`, for example (start and end angle, or start and delta)

**Comment by fenjalien** [comment]
Hm, we don't have it documented but arcs have additional anchors "start", "end" and "origin". With these you can use the `anchor` parameter and the arc will be positioned relative to the given anchor. So `arc((0,0), anchor: "origin")` should work. We don't have these documented though...

**Comment by johannes-wolf** [comment]
I propose adding a function to draw an arc from point a to c through b.

**Comment by johannes-wolf** [comment]
I've added the missing documentation.
