### ISSUE TITLE
Manual installation fails on Mac 

### ISSUE THREAD

**Issue by xosxos** [johannes-wolf/cetz#203]
I installed this on Ubuntu 22.04 and it was flawless. On the other hand, when installing on a M2 Mac (the default bash version is `3.2.57` i.e. very old) by running the `./scripts/package script` I ran into the following issues:

1. I got an error for `#!/bin/env bash` env not being found. This was fixed by changing to `"#!/bin/bash"`. I am not sure of the downsides.

2. On line 58 `cp -r` throws an error if the `-r` parameter is not directly after the `cp` command.

3. The `awk` command `regexp` leaves an `"` to the beginning of the version directory name.

For now, this is just an FYI and a notice to Mac users (I don't know if fixes for old GNU software causes regression in new versions). Also, the automatic download and installation of `@preview/cetx:0.1.1` compiles all examples without an issue.

**Comment by johannes-wolf** [comment]
Hi, thanks for reporting this. Can you take a look at the changes in PR #205, please?
I have no mac to test it with, so I would appreciate it if you could do that.
