### ISSUE TITLE
Add ability to draw chart and plot on the same figure more easily (more flexible plot config)

### ISSUE THREAD

**Issue by Andrew15-5** [johannes-wolf/cetz#214]
```typ
#cetz.canvas({
  import cetz.draw: *
  import cetz.chart
  let old-mid-points = mid-points
  let mid-points = mid-points.map(point => calc.round(point, digits: 2))
  let data = mid-points.zip(interval-hits)
  let plot-height = 4
  let plot-width = 15
  chart.columnchart(size: (plot-width, plot-height), bar-width: 1, data)
  import cetz.plot
  set-style(axes: (
    mark: (end: none),
    stroke: none,
    tick: (stroke: none, label: (offset: 0)), // `tick: none` doesn't work
  ))
  plot.plot(
    size: (plot-width, plot-height), // How to make plot take the same size as canvas already has (with the columnchart)?
    y-min: 0,
    y-max: max-hits,
    x-min: 0 + 0.08,
    x-max: max + 0.065,
    tick-step: 100, // This does nothing.
    y-tick-step: 100, // How to just remove all ticks?
    x-tick-step: 100,
    x-label: none, // Why I can't just use `label: none`?
    y-label: none,
    axis-style: "school-book",
    {
      plot.add(data, style: (stroke: 2pt))
    },
  )
})
```

![image](https://github.com/johannes-wolf/cetz/assets/37143421/ed0bdf8a-3b8e-4675-8671-829bace0bd94)

As you can see in this block of code, there are some offsets and repetitions (and other workarounds). But the result is still not perfect (it's far from the ease and beauty of matplotlib). Why I can't remove zero from the plot?

P.S. I encounter much more problems with this, but they probably should be in separate issues.

**Comment by johannes-wolf** [comment]
Could you please give a working code example, including your data variables?
You can remove the zero. Remove ticks by setting `x-tick-step: none` and `y-tick-step: none`.

The `chart` library is not really meant to get mixed with `plot`, although it seems to work. With current master, you can also plot "stepped" plots, with `line: "vhv"`.

**Comment by johannes-wolf** [comment]
If you want matplotlib, use matplotlib. This lib is not a replacement for, nor is it inspired by matplotlib or anything else. If you have certain features in mind, feel free to open a PR.

**Comment by Andrew15-5** [comment]
> You can remove the zero. Remove ticks by setting `x-tick-step: none` and `y-tick-step: none`.

Setting `tick-step` to `none` did remove the `0`, but it's not present in release/dev manual:
![image](https://github.com/johannes-wolf/cetz/assets/37143421/a58fab09-3306-4447-8705-97c2973b1296)

> you can also plot "stepped" plots, with `line: "vhv"`.

I have no idea what this means and how such line types are possible:
![image](https://github.com/johannes-wolf/cetz/assets/37143421/c847bd98-68a7-4485-8a59-ed76a8d1ae5d)

It must have an example, otherwise it's hard (impossible) to understand (for me).

> You could also try using `on-layer`

This is a very useful feature, I assume. But what benefit will it give for my example? I don't think there will be any difference.

**Comment by Andrew15-5** [comment]
> This lib is not a replacement for, nor is it inspired by matplotlib or anything else

Are you sure it's not inspired by the tikz? Anyway, maybe being a Typst's matplotlib is a super high level to reach, but in comparison to tikz it also loses by a lot. The main issue is that cetz is too new to be comparable with mature libraries, and I just want to have a full Typst replacement right here and right now... The Typst itself only exists for half of the year.

**Comment by Andrew15-5** [comment]
> Could you please give a working code example, including your data variables?

You will be sorry you asked that. /s Because the data is being processed a lot. So it's easier to just cut everything from the beginning and the end and give a table with data and the histogram+graph: [214.zip](https://github.com/johannes-wolf/cetz/files/12708419/214.zip)

**Comment by johannes-wolf** [comment]
> Are you sure it's not inspired by the tikz?
Yeah, that was dumb of me to say. It is inspired by tikz but without the goal of feature parity.

Thank you. I think it would be better adding bar-charts to the plot API. I wanted to add more plotting-types anyway.

**Comment by johannes-wolf** [comment]
Closing this. The plot API will get lots of additions in 0.2.0 and will get bar/colum support in the future.

An option to overlay plot and chart is not planned.
