### ISSUE TITLE
How to use plot.add-anchor

### ISSUE THREAD

**Issue by scrouthtv** [johannes-wolf/cetz#223]
Hello,

I am currently trying to create a scatter plot. My goal would be to
1. create a `plot.plot` environment
2. place some anchors on it
3. add content to these anchors
However, I am having problems using the `add-anchor` function. It would either fail with some weird error message (e.g. `missing argument name, same issue as in #172) or place the anchor at weird positions or not at all.

Here is my current attempt:
```rust
#import "@preview/cetz:0.1.0"

#figure(cetz.canvas({
    import cetz.draw
    import cetz.plot

    plot.plot(size: (7, 4), axis-style: "left", x-min: 0, x-max: 10, y-min: 0, y-max: 10, {
        plot.add(domain: (0, 1), x => 1) // need this or plot would not render at all (?)

        plot.add-anchor("x", (6, 2))

    })

    draw.content("x", [asdf])
}))
```

Giving me `error: assertion failed: Unknown element 'x' in elements ()`.

I can't move the `draw.content` inside the plot either, as I can only call `plot.*` subcommands inside the plot environment.

What am I doing wrong?
 - How would one use the `add-anchor` functionality?
 - Does it have to be inside or outside the `plot` environment?
 - I think it would be great if you could add an example to the manual.pdf

**Comment by johannes-wolf** [comment]
You have to give your `plot` element a name i.e. `name: "plot"`. Than you can access the anchor using `"plot.x"`.

```typst
#import "@preview/cetz:0.1.1"

#figure(cetz.canvas({
    import cetz.draw
    import cetz.plot

    plot.plot(size: (7, 4), axis-style: "left", x-min: 0, x-max: 10, y-min: 0, y-max: 10, name: "plot", {
        plot.add(domain: (0, 1), x => 1) // need this or plot would not render at all (?)

        plot.add-anchor("x", (6, 2))

    })

    draw.content("plot.x", [asdf])
}))
```

**Comment by johannes-wolf** [comment]
That you need at least one `plot.add` is a bug. If you only want to draw axes, without using the plot API, use the `axes` API (see `src/lib/axes.typ`).

**Comment by scrouthtv** [comment]
Perfect, thank you.
