### ISSUE TITLE
Remove/fix the default anchor of intersections

### ISSUE THREAD

**Issue by TimotheAlbouy** [johannes-wolf/cetz#228]
When we compute the intersections of several elements, the intersections element gets an additional `default` anchor that we may not want. I think that this anchor is initialized to the `default` anchor of the first element given to the `intersections()` function (in the below example, this element is the left circle).

```typst
#import "@preview/cetz:0.1.1"

#cetz.canvas({
  import cetz.draw: *
  intersections(name: "i", {
    circle((0,0))
    circle((1,0))
  })
  for-each-anchor("i", (name_anchor) => {
   content((), [#name_anchor])
  })
})
```

![image](https://github.com/johannes-wolf/cetz/assets/38692015/e409c7c1-143f-41fb-a5c6-faded4a625fe)

I think that this default anchor should be either removed or initialized to a meaningful value, such as the first intersection for example (in this example, `i.0`). I have a preference for removing it altogether, because otherwise it begs the question, what is the default anchor when there is no intersection? Moreover, when we are iterating over the anchors of the intersections element like we are doing in the example, we would display two times the first anchor (the first time with `i.0`, and the second time with `i.default`).

So I suggest to remove completely the `i.default` anchor of intersections elements `i`.

Associated [Discord thread](https://discordapp.com/channels/1054443721975922748/1157346054619017336).

**Comment by johannes-wolf** [comment]
Fixed with #257.
