### ISSUE TITLE
Compute the intersections of elements using their names

### ISSUE THREAD

**Issue by TimotheAlbouy** [johannes-wolf/cetz#230]
Currently, to compute the intersections of some elements, we pass the elements directly to the body argument of the `intersections()` function. However, this has several disadvantages.

Firstly, it is not possible to compute the intersections of elements that were already displayed before calling `intersections()` without displaying the elements a second time, which produces uglier edges on the elements. See [this Discord thread](https://discordapp.com/channels/1054443721975922748/1157333272959914004) for more info.

Secondly, it means that if we do a function that computes the intersections of several elements, then we HAVE to pass these elements directly, and not just their names. This, I think, goes against the design principles of the library, as the name is the idiomatic way of referring to an element in CeTZ (e.g., we pass names to the `line()` function, not elements directly). Moreover, we have no way of retrieving an element using just its name in CeTZ (even using the context). See [this Discord thread](https://discordapp.com/channels/1054443721975922748/1157346054619017336) for more info.

So for me, the solution would be to change how the `intersections()` function works, and pass as parameters just names and not elements.

**Comment by TimotheAlbouy** [comment]
Ok so I think I get why intersections were not computed by element names before, it's because CetZ does not store anything on the elements apart of their anchors. But to compute the intersections of elements, you need more than just their anchors, you also need their path, which is not stored anywhere. That was a design choice, but it turned out to be sub-optimal in this case... The only way I see this fixed would be by exposing the entire elements in the context, either through `ctx.nodes` (but this would require some refactoring everywhere `ctx.nodes` is used, see #229) or by adding a new attribute, like idk `ctx.full_elements`.

**Comment by johannes-wolf** [comment]
Storing the path along the anchors should be no problem. I suggest waiting for @fenjalien's PR #221 before doing anything on this.

**Comment by johannes-wolf** [comment]
`intersections(..)` now accepts names in addition to elements.
