### ISSUE TITLE
How to set axis bounds?

### ISSUE THREAD

**Issue by SUPERCILEX** [johannes-wolf/cetz#241]
```
      chart.columnchart(
        y-tick-step: 0.2,
        (([$cal(P)_+$], 4 / 13), ([$cal(P)_-$], 9 / 13))
      )
```

I'd like to make the y axis end at 1.0, but that doesn't seem possible?

**Comment by johannes-wolf** [comment]
I have added `x-max`/`y-max` to `barchart`/`columnchart` to allow setting the maximum value.

**Comment by SUPERCILEX** [comment]
Awesome, thanks!
