### ISSUE TITLE
plot: Improve contour plots

### ISSUE THREAD

**Issue by Andrew15-5** [johannes-wolf/cetz#270]
I'm really happy that we went from 0 to 60 (percent) real quick (#215). But it still has a lot of rough edges. So I figured, that I will list them here and then probably convert it to a tracking issue (of dependency sub-issues).

Notes:
- all "formulas" are assumed to be prefixed with `(x, y) => `;
- some of them are simplified (not the same as in the plot example) to simply convey the main idea.
- struck out items mean that "it is not the intended usage" (see a note below such an item).

Issues that must be fixed (high priority):
- Straight lines are offsetted.
  - <strike>No issues with conditionals (`x >= 0`, `y >= 0`, `x == y`).</strike>
    Note: boolean usage is discouraged (see [this](https://github.com/johannes-wolf/cetz/issues/270#issuecomment-1773925210) and [this](https://github.com/johannes-wolf/cetz/issues/270#issuecomment-1773934945)).
  - [x] `x` is now showing as `x = 1` (offsets by `+1` to the right) and `y` is now showing as `y = 1` (offsets by `+1` to the top).
    Note: if `z: 0` then it works correctly (default is `z: 1`, at least at the time of testing).
- Circle is filling outside the contour.
  - <strike>Correctly fills if `9 - x² + y²` (which is `9 = x² + y²` or a positive float).</strike>
    Note: use `x² + y²` and `z: 9` (for the right-hand side) instead.
  - <strike>Correctly fills if `x² + y² <= 9`.</strike>
    Note: boolean usage is discouraged (see [this](https://github.com/johannes-wolf/cetz/issues/270#issuecomment-1773925210) and [this](https://github.com/johannes-wolf/cetz/issues/270#issuecomment-1773934945)).
  - [x] <strike>Doesn't work if `x² + y² - 9` (which is `x² + y² = 9` or a negative float).</strike>
    Note: use `x² + y²` and `z: 9` (for the right-hand side) instead.
- [x] <strike>Circle contour is wrong if `bool` is returned `bool` (`x² + y² <= 9`).</strike>
  Note: boolean usage is discouraged (see [this](https://github.com/johannes-wolf/cetz/issues/270#issuecomment-1773925210) and [this](https://github.com/johannes-wolf/cetz/issues/270#issuecomment-1773934945)).
- [x] <strike>Hyperbola contour is wrong if `bool` is returned `bool` (`x ⋅ y >= 1`).</strike>
  Note: boolean usage is discouraged (see [this](https://github.com/johannes-wolf/cetz/issues/270#issuecomment-1773925210) and [this](https://github.com/johannes-wolf/cetz/issues/270#issuecomment-1773934945)).
- [x] <strike>Hyperbola contour is inverted if `1 - x ⋅ y` (negative float), but it's correct if `x ⋅ y - 1` (positive float).</strike>
Note: use `x ⋅ y` and `z: 1` (for the right-hand side) instead.

Issues that should be fixed (medium priority):
- [x] `x` can only fill to the right and `y` can only fill to the top (same with `x - y`).
  This probably can only be fixed (ideally) with `x <= 0`/`y <= 0`, i.e., changing return value from `float` to `bool`.
  Note: <strike>logical/boolean operators (conditionals) are already supported and</strike> with the right value for `x-domain`/`y-domain` the fill direction is correct. Use a new `op: "<="` (or `">="`) option and leave `x`/`y` as is.
- [ ] Contour for `x` and `y` is drawn as a C and U (sometime even O) shapes instead of straight lines (with limited length).

Features that are nice to have (low priority):
- [ ] Can't get intersection points (and their coordinates).
- [x] Multiple layers of fill don't blend/mix.
  Note: use `style: (line: (stroke: rgb("#378A467F"), fill: rgb("#378A467F").lighten(25%)))` inside the `add-contour` (see [`rgb()`](https://typst.app/docs/reference/visualize/color/#definitions-rgb)).

This issue was created after testing against the [`master#0a92100`](https://github.com/johannes-wolf/cetz/commit/0a9210095e72ec081ef9bc8a707142ef25f6aa65). The base code through which all of the above problems/missing features were discovered:

<details><summary>base.typ</summary>

```typ
#import "@local/cetz:0.1.2"

#set page(fill: black)
#set text(fill: white)

#cetz.canvas({
  import cetz.draw: *
  import cetz.plot
  let get-style(color) = (line: (stroke: color, fill: color.lighten(75%)))
  plot.plot(size: (15, 15), {
    // x >= 0
    plot.add-contour(
      (x, y) => x + 1,
      x-domain: (0, 10),
      y-domain: (-10, 10),
      fill: true,
      style: get-style(green),
    )

    // y >= 0
    plot.add-contour(
      (x, y) => y + 1,
      x-domain: (-10, 10),
      y-domain: (0, 10),
      fill: true,
      style: get-style(purple),
    )

    // hyperbola
    plot.add-contour(
      (x, y) => (x - 1) * (y - 1) - 1,
      x-domain: (-10, 10),
      y-domain: (-10, 10),
      fill: true,
      style: get-style(red),
    )

    // circle
    plot.add-contour(
      (x, y) => calc.pow((x - 1), 2) + calc.pow((y - 1), 2) - 9,
      x-domain: (-10, 10),
      y-domain: (-10, 10),
      // fill: true, // Paint outside of the circle
      style: get-style(blue),
    )

    // line
    plot.add-contour(
      (x, y) => x + 1 - y,
      x-domain: (-10, 10),
      y-domain: (-10, 10),
      style: get-style(black),
    )
  })
})
```

</details>

<details><summary>Plot screenshot</summary>

![image](https://github.com/johannes-wolf/cetz/assets/37143421/27de29b2-f2de-41d5-84fc-47fdfc3202e2)

</details>

<details><summary>Reference screenshots from Desmos</summary>

![image](https://github.com/johannes-wolf/cetz/assets/37143421/f137bdba-454b-454d-8776-521745cd2f9c)

![image](https://github.com/johannes-wolf/cetz/assets/37143421/bdb02515-5158-4de5-acbe-9ebab4db910f)

![image](https://github.com/johannes-wolf/cetz/assets/37143421/5b3582eb-5da5-4221-bdaf-ab51f5f05282)

</details>

---
### New issues after testing against [`redesign-internals#742d560`](https://github.com/johannes-wolf/cetz/pull/271/commits/742d560a9579ab43cc75eb3cb7af5606c1084908).

- [ ] When using `op: "=="` to plot straight lines (`x - y` + `z: 0`) nothing is plotted (the line isn't present).
- [ ] When using `x² + y²` + `op: ">="` + `z: 9` + `fill: true` it fills outside the circle **and inside** of it (although it works as expected with hyperbola). #277
- [x] With `style: (line: (stroke: color + 1em, fill: color))` (for `add-contour()`) instead of adding thickness to the contour line (border) it also increases area of the fill, including outside the borders:
  <details><summary>screenshot</summary>

  
  ![image](https://github.com/johannes-wolf/cetz/assets/37143421/59a6db33-8241-4d79-ac4d-bdd3994bf6f4)

  </details>
  <details><summary>code</summary>

  ```typ
  #import "@local/cetz:0.1.2"
  
  #cetz.canvas({
    import cetz.draw: *
    import cetz.plot
    // let get-style(color) = (line: (stroke: color, fill: color.lighten(25%)))
    let get-style(color) = (line: (stroke: color + 1em, fill: color.lighten(25%)))
    plot.plot( size: (15, 15), axis-style: "school-book", {
      // x >= 0
      plot.add-contour(
        (x, y) => x,
        z: 0,
        x-domain: (0, 15),
        y-domain: (-1, 1),
        fill: true,
        style: get-style(rgb("#378A467F")),
      )
  
      // hyperbola
      plot.add-contour(
        (x, y) => (x - 1) * (y - 1),
        z: 20,
        x-domain: (-15, 15),
        y-domain: (-15, 15),
      )
    })
  })
  ```

  </details>
  Note: I forgot to remove transparency of the contour line. Use this:

  ```typ
  #let get-style(color) = {
    let (r, g, b, ..) = color.to-rgba()
    (line: (stroke: rgb(r, g, b) + 1em, fill: color.lighten(25%)))
  }
  ```
- [x] In the above scenario, the thickened contour stroke is added to the right of the RHS, instead of the center.
  Note: this is a blending effect, not a bug, see note of the task above.

**Comment by Andrew15-5** [comment]
@johannes-wolf, tell me if I should create a separate issue for every task (now or later) and do I need to add anything else (implementation optimizations or something like that).

**Comment by johannes-wolf** [comment]
You can get a correct looking result with:
```typst
#import "src/lib.typ"
#let cetz = lib

#cetz.canvas({
  import cetz.draw: *
  import cetz.plot
  let get-style(color) = (line: (stroke: color, fill: color.lighten(75%)))
  plot.plot(size: (15, 15), {
    // x >= 0
    plot.add-contour(
      (x, y) => x >= 0,
      x-domain: (0, 10),
      y-domain: (-10, 10),
      fill: true,
      style: get-style(green),
    )

    // y >= 0
    plot.add-contour(
      (x, y) => y >= 0,
      x-domain: (-10, 10),
      y-domain: (0, 10),
      fill: true,
      style: get-style(purple),
    )

    // hyperbola
    plot.add-contour(
      (x, y) => (x - 1) * (y - 1),
      x-domain: (-10, 10),
      y-domain: (-10, 10),
      fill: true,
      z: 1,
      style: get-style(red),
    )

    // circle
    plot.add-contour(
      (x, y) => 9 - (calc.pow((x - 1), 2) + calc.pow((y - 1), 2)),
      x-domain: (-10, 10),
      y-domain: (-10, 10),
      z: 0,
      fill: true,
      style: get-style(blue),
    )

    // line
    plot.add-contour(
      (x, y) => x + 1 - y,
      x-domain: (-10, 10),
      y-domain: (-10, 10),
      style: get-style(black),
    )
  })
})
```

![grafik](https://github.com/johannes-wolf/cetz/assets/519002/6fcdd481-79f6-4ccf-80bf-22b76793b8fd)

The offset of `x` and `y` for non-boolean is incorrect. I will take a look into that. It is a bog with the domain! If you set the lower domain limit != 0 it works.

**Comment by johannes-wolf** [comment]
Please test against branch `redesign-internals` as this one is becoming 0.2.0.

**Comment by johannes-wolf** [comment]
> Issues that should be fixed (medium priority):
> - [ ] `x` can only fill to the right and `y` can only fill to the top (same with `x - y`).
  This probably can only be fixed (ideally) with `x <= 0`/`y <= 0`, i.e., changing return value > from `float` to `bool`.
> - [ ] Contour for `x` and `y` is drawn as a C and U shapes instead of straight lines with limited length.
Can you give examples for those?

**Comment by johannes-wolf** [comment]
You can use a color with transparency to get blending.

**Comment by johannes-wolf** [comment]
Or did you mean, that plots with holes do not work? This is true, the hole gets stroked, but everything gets filled.

**Comment by Andrew15-5** [comment]
I will go through all your comments later. In the meanwhile, please check the updated OP. I expanded it and included what you showed here: https://github.com/johannes-wolf/cetz/issues/270#issuecomment-1773886783. But overall the issues are still present, except this one:

> `x` can only fill to the right and `y` can only fill to the top (same with `x - y`).
> This probably can only be fixed (ideally) with `x <= 0`/`y <= 0`, i.e., changing return value from `float` to `bool`.
> Note: logical/boolean operators (conditionals) are already supported and with the right value for `x-domain`/`y-domain` the fill direction is correct.

**Comment by johannes-wolf** [comment]
> x is now showing as x = 1 (offsets by +1 to the right) and y is now showing as y = 1 (offsets by +1 to the top).

Are you setting `z: 0`? Because it defaults to `1` which explains the behavior.

> Circle contour is wrong if bool is returned bool (x² + y² <= 9).
> Hyperbola contour is wrong if bool is returned bool (x ⋅ y >= 1).

Unfixable, do not use booleans. Use the new operator support + z: `z: 9, op: "<="` and `z: 1, op: ">="`. See/use my PR for testing, as this is a new feature.

I think in some cases you are not using the correct z value(s).

**Comment by Andrew15-5** [comment]
> Are you setting `z: 0`? Because it defaults to `1` which explains the behavior.

With `z: 0` the line is closer to zero, but now it's in the negative half.

<details><summary>source</summary>

```typ
    // x >= 0
    plot.add-contour(
      (x, y) => x,
      z: 0,
      x-domain: (0, 10),
      y-domain: (-10, 10),
      fill: true,
      style: get-style(green),
    )

    // y >= 0
    plot.add-contour(
      (x, y) => y,
      z: 0,
      x-domain: (-10, 10),
      y-domain: (0, 10),
      fill: true,
      style: get-style(purple),
    )
```

![image](https://github.com/johannes-wolf/cetz/assets/37143421/6ad74d62-edf6-41ee-a5c9-1fd6a6fb9b26)

</details>

> Unfixable, do not use booleans. Use the new operator support + z: `z: 9, op: "<="` and `z: 1, op: ">="`. See/use my PR for testing, as this is a new feature.
> 
> I think, in some cases you are not using the correct z value(s).

Whaa? I thought `z` is background/foreground index (`z-index` in CSS). Yeah, `op` wasn't there, so I need to check it out (later). So you are saying that you **never ever** should use boolean expression when plotting contours? Only function with a returned number + `z` and `op`? I mean that is this applied to any contour or only circle/hyperbola?

**Comment by johannes-wolf** [comment]
Have you tested with the branch from the PR?
Yes, no booleans. It can not work, because the sampled matrix is a matrix of booleans, this means interpolation does not work at all. I mean you can use bools, but you have to use a high sample number to get pleasing results.

**Comment by Andrew15-5** [comment]
> > Issues that should be fixed (medium priority):
> > 
> > * [ ]  `x` can only fill to the right and `y` can only fill to the top (same with `x - y`).
> >   This probably can only be fixed (ideally) with `x <= 0`/`y <= 0`, i.e., changing return value > from `float` to `bool`.
> > * [ ]  Contour for `x` and `y` is drawn as a C and U shapes instead of straight lines with limited length.
> 
> Can you give examples for those?

The first one is already resolved.

for the second one just use smaller domain than the canvas:

<details><summary>code</summary>

```typ
plot.add-contour(
  (x, y) => x,
  z: 0,
  x-domain: (0, 10),
  y-domain: (-1, 1),
  fill: true,
)
```

</details>

![image](https://github.com/johannes-wolf/cetz/assets/37143421/674edeb2-dd25-462e-bac9-ecfce4396219)

I would increase border/contour thickness, but it has a weird bug (which isn't noted), or I do something wrong:


<details><summary>code</summary>

```typ
#cetz.canvas({
  import cetz.draw: *
  import cetz.plot
  let get-style(color) = (line: (stroke: color + 1em, fill: color))
  // let get-style(color) = (line: (stroke: color, fill: color.lighten(25%)))
  plot.plot(size: (15, 15), axis-style: "school-book",
  {
    // x >= 0
    plot.add-contour(
      (x, y) => x,
      z: 0,
      x-domain: (0, 10),
      y-domain: (-1, 1),
      fill: true,
      style: get-style(rgb("#378A467F")),
    )

    // hyperbola
    plot.add-contour(
      (x, y) => (x - 1) * (y - 1),
      z: 19,
      x-domain: (-10, 10),
      y-domain: (-10, 10),
      x-samples: 50,
      y-samples: 50,
      fill: true,
      style: get-style(rgb("#C8423F7F")),
    )
  })
})
```

</details>

![image](https://github.com/johannes-wolf/cetz/assets/37143421/51f49d95-c079-4832-af07-568143f16ee4)

Oh, right, it's not C/U, it's actually O (closed path), at least with big thickness. It supposed to be one line along `x == 0` and just the `fill` color to the right (not both).

**Comment by Andrew15-5** [comment]
This is as close as I could get to the first Desmos screenshot:

<details><summary>code</summary>

```typ
#import "@local/cetz:0.1.2"

#set page(width: 16.13cm, height: 14.03cm, margin: 0pt)
#set box(inset: -1em)

#cetz.canvas({
  import cetz.draw: *
  import cetz.plot
  // Bug with thickness.
  // let get-style(color) = (line: (stroke: color + 1em, fill: color.lighten(25%)))
  let get-style(color) = (line: (stroke: color, fill: color.lighten(25%)))
  set-style(axes: (
    tick: (stroke: none),
    stroke: none,
    // grid: (stroke: yellow), // Doesn't work.
  ))
  let x-min = -8
  let x-max = 15
  let y-min = -10
  let y-max = 10
  let width = x-max - x-min
  let height = y-max - y-min
  let factor = 0.7
  width = width * factor
  height = height * factor
  plot.plot(
    size: (width, height),
    axis-style: "school-book",
    x-label: none,
    y-label: none,
    x-tick-step: none,
    y-tick-step: none,
    x-ticks: range(-1, 3).map(it => it * 5),
    y-ticks: range(-1, 2).map(it => it * 5),
  {
    // hyperbola
    plot.add-contour(
      (x, y) => (x - 1) * (y - 1),
      z: 1,
      x-domain: (x-min, x-max),
      y-domain: (y-min, y-max),
      x-samples: 50,
      y-samples: 50,
      fill: true,
      style: get-style(rgb("#C8423F7F")), // red
    )

    // circle
    plot.add-contour(
      (x, y) => (calc.pow((x - 1), 2) + calc.pow((y - 1), 2)),
      op: "<=",
      z: 9,
      x-domain: (x-min, x-max),
      y-domain: (y-min, y-max),
      x-samples: 50,
      y-samples: 50,
      fill: true,
      style: get-style(rgb("#2D6FB47F")), // blue
    )

    // x >= 0
    plot.add-contour(
      (x, y) => x,
      z: 0,
      x-domain: (0, x-max),
      y-domain: (y-min, y-max),
      fill: true,
      style: get-style(rgb("#378A467F")), // green
    )

    // y >= 0
    plot.add-contour(
      (x, y) => y,
      z: 0,
      x-domain: (x-min, x-max),
      y-domain: (0, y-max),
      fill: true,
      style: get-style(rgb("#6042A57F")), // purple
    )

    // x (y = x)
    plot.add(domain: (x-min, y-max), x => x, style: (stroke: black))

    // `op: "=="` doesn't work.
    // x (y = x)
    // plot.add-contour(
    //   // (x, y) => x == y,
    //   (x, y) => x - y,
    //   // op: "==",
    //   z: 0,
    //   x-domain: (x-min, x-max),
    //   y-domain: (y-min, y-max),
    //   // style: get-style(black),
    //   style: get-style(rgb("#0000007F")),
    // )
  })
})
```

</details>

<details><summary>screenshot</summary>

![image](https://github.com/johannes-wolf/cetz/assets/37143421/c8974824-9447-4f17-af7c-d3e573a26ffb)

</details>

The main visual problem is that I couldn't (for some reason) add a `grid`. Could you please help me with that?

**Comment by johannes-wolf** [comment]
> > > Issues that should be fixed (medium priority):
> > > 
> > > * [ ]   `x` can only fill to the right and `y` can only fill to the top (same with `x - y`).
> > >   This probably can only be fixed (ideally) with `x <= 0`/`y <= 0`, i.e., changing return value > from `float` to `bool`.
> > > * [ ]   Contour for `x` and `y` is drawn as a C and U shapes instead of straight lines with limited length.
> > 
> > 
> > Can you give examples for those?
> 
> The first one is already resolved.
> 
> for the second one just use smaller domain than the canvas:
> code
> 
> ```typst
> plot.add-contour(
>   (x, y) => x,
>   z: 0,
>   x-domain: (0, 10),
>   y-domain: (-1, 1),
>   fill: true,
> )
> ```
> 
> ![image](https://user-images.githubusercontent.com/37143421/277194170-674edeb2-dd25-462e-bac9-ecfce4396219.png)
> 
> I would increase border/contour thickness, but it has a weird bug (which isn't noted), or I do something wrong:
> code
> 
> ![image](https://user-images.githubusercontent.com/37143421/277194251-51f49d95-c079-4832-af07-568143f16ee4.png)
> 
> Oh, right, it's not C/U, it's actually O (closed path), at least with big thickness. It supposed to be one line along `x == 0` and just the `fill` color to the right (not both).

The problem here is, that the sampled domain is the visible domain. Since the function gets sampled between [0, 10] it can not know that there are no vertical "borders" because no values outsides that range are known. A solution would be having a bigger sample-domain and not showing the fully sampled domain. We could add a flag "oversample" that samples left and right of the sampling domain, bot not modifying the visible domain?

**Comment by Andrew15-5** [comment]
Let's test this. But the problem here is that not only it shows right vertical line, it also shows top and bottom one. So the flag should "oversample" left, right, **top and bottom**.

I still don't get why the area of the `fill` color is also expanded as the contour `stroke` is thickened? I think this is a clear bug.
![image](https://github.com/johannes-wolf/cetz/assets/37143421/23fe4f09-2f1f-4b4d-9d52-dd7dbf080be6)

And you can also see that the thick contour `stroke` is fully drawn at `x => 0` instead of dead center of the `x == 0`, you know? Usually, when you draw a thick line, the center of that thick line should go right where the center of the thin line is. In the screenshot, the center of the thick `(x, y) => x` (+ `op: ">="` + `z: 0`) line is not aligned with the center of the Y axis thin line.

**Comment by johannes-wolf** [comment]
> When using op: "==" to plot straight lines (x - y + z: 0) nothing is plotted (the line isn't present).

This is expected and has to do with sampling. The sampling is not "hitting" the values where the function is zero. We _could_ either allow `op: ` to be of type function so the user can code his/her own comparison including an epsilon or have an epsilon attribute.

**Comment by johannes-wolf** [comment]
>  When using x² + y² + op: ">=" + z: 9 + fill: true it fills outside the circle and inside of it (although it works as expected with hyperbola).

This is _very_ complicated to solve as of now. Please create a separate ticket for this.

**Comment by Andrew15-5** [comment]
> This is strange as I can not reproduce it.

Shoot, I really should've thought this through. I didn't remove alpha from contour stroke, so the contour thick line mixed with the inner fill, created in 2 layers of the same transparent color making an illusion that the fill has exceeded its area and the stroke is offsetted inside. My bad. Here is the fixed `get-style()`:

```typ
#{
  let get-style(color) = {
    let (r, g, b, ..) = color.to-rgba()
    (line: (stroke: rgb(r, g, b) + 1em, fill: color.lighten(25%)))
  }
}
```

> added the option to pass a function `(z0, z1) => boolean` to `op:` to support custom comparison.

Hmm, it does work, but what do the arguments mean? What exactly do we compare? This works ok: `op: (l, r) => calc.abs(r - l) < 1`, but you can see the unwanted extra lines alongside the canvas border:
![image](https://github.com/johannes-wolf/cetz/assets/37143421/7bc44a6d-9671-4b40-81fa-513fef2cfbdc) ![image](https://github.com/johannes-wolf/cetz/assets/37143421/8b114fbe-c6c3-4336-bb56-d39fa4210511)

It's kinda confusing since the `op` is supposed to be an operator, logical operator: "<=", ">=", "==". When you give it the function with arguments, it obscures the meaning, IMO.

**Comment by Andrew15-5** [comment]
> the second is the z value of your data

Hold on, which data? I only pass a function and about 6 named arguments. Do I miss something obvious?

> you can pass an array of values to `z:` to plot multiple contours per data.

Wow, I can actually plot 2 circles for the price of one with `z: (9, 16)`. This is pretty cool stuff.

**Comment by johannes-wolf** [comment]
> > the second is the z value of your data
> 
> Hold on, which data? I only pass a function and about 6 named arguments. Do I miss something obvious?

The matrix of the sampled values. But you can also pass a matrix as an array of arrays of numbers if you want to.

> 
> > you can pass an array of values to `z:` to plot multiple contours per data.
> 
> Wow, I can actually plot 2 circles for the price of one with `z: (9, 16)`. This is pretty cool stuff.

Yes, take a look at the test images here: https://github.com/johannes-wolf/cetz/pull/271/files#diff-c42484ff5212737b6f585e90895e76fde4994035aa35f36f1ebb8e898c2d8ec1
(you have to pay for the contour finding per z-value, though!)

**Comment by Andrew15-5** [comment]
> you have to pay for the contour finding per z-value, but not the sampling

I was referring to the count of `add-contour()` compared to the count of drawn circles. But it's nice that sampling is only "paid" once as well. The only price to pay is that `style` is shared between all the circles.

**Comment by johannes-wolf** [comment]
The way to get rid of them is fixing your x-min/x-max y-min/y-max to a value so that the domain is outsides that window.

**Comment by Andrew15-5** [comment]
This is also known as hacking. The problem is that the API is supposed to be created for the user to use, so it should be straightforward. But a lot of time the API is either not flexible enough **yet** or **for eternity**. I've encountered this kind of plotting hacking where the output isn't really what it should have been, so you are trying hard to get it work just like you wanted by making a lot of hacky stuff, like instead of defining range for an axis from -15 to +15, you define it as [-14.6; +14.6], so that the `15` on the plot wouldn't show up (at all) in the unreadable manner (like when the number is smashed on top of the tick which makes it unreadable or ugly).

This problem has the same idea. I will try changing the domain values, but you already said about "oversampling", if I'm understanding correctly, it will do the same thing as what you have just said (about domain). So try implementing such a thing, and we will then test it and see if it's good or not.

**Comment by johannes-wolf** [comment]
I checked against matplotlib output and I will try to replicate the edge behavior (soonish).
