### ISSUE TITLE
Re-export src/util.typ

### ISSUE THREAD

**Issue by JamesxX** [johannes-wolf/cetz#272]
https://github.com/johannes-wolf/cetz/blob/0a9210095e72ec081ef9bc8a707142ef25f6aa65/src/lib.typ#L1-L10

I'm working on making my package more compatible with cetz styles and I find myself needing what would be `cetz.util.merge-dictionary`. I could copy over the function myself but it would be better practice if I loaded it from the cetz package

**Comment by johannes-wolf** [comment]
Is using `styles.resolve(...)` an option? This function handles style resolving + injection for you. I would actually like to keep stuff in `util.typ` private to be able to change API without breaking other libs.

**Comment by johannes-wolf** [comment]
Closing this, as you copied the function into your project.
