### ISSUE TITLE
Plot Mark styling doesn't work

### ISSUE THREAD

**Issue by Suyashtnt** [johannes-wolf/cetz#286]
rt

Even shows in the manual:
![image](https://github.com/johannes-wolf/cetz/assets/45307955/7c03d17e-dbdb-42df-8d51-2a0769cfe0f6)

**Comment by johannes-wolf** [comment]
Thank you. There is a `mark-style:` option for `add(...)`, so I think the manual is wrong here.

**Comment by Suyashtnt** [comment]
> Thank you. There is a `mark-style:` option for `add(...)`, so I think the manual is wrong here.

It doesn't seem to work either way
![image](https://github.com/johannes-wolf/cetz/assets/45307955/b45140a2-0cd1-4fd2-b078-4264a95b9f26)

**Comment by johannes-wolf** [comment]
There is no "mark" sub-element for the mark-style. Correct would be i.e.: ` mark-style: (stroke: red)`. Note that you can not fill the `"x"` mark, so setting a fill color does nothing.
