### ISSUE TITLE
Allow `mark.draw-mark` to take a function for mark-size

### ISSUE THREAD

**Issue by JamesxX** [johannes-wolf/cetz#298]
https://github.com/johannes-wolf/cetz/blob/edea3b22c6fc5b14829d09c55de8ca0c530abbfe/src/lib/plot/mark.typ#L3-L9

If `mark.draw-mark` is rewritten to allow for indexed mark sizes, bubble charts would be much easier and less costly to implement, but would mean refactoring.

**Comment by johannes-wolf** [comment]
Yes, it should get rewritten. I think it should allow for indexed size + styles (stroke-color, fill-color). There should also be a more clean mechanism for plots to set marks. Maybe an extra `add-scatter`, that gets called by `add()` if the mark property is set.

**Comment by JamesxX** [comment]
Styles is also a good shout, didn't see your comment by the time I made the PR

**Comment by johannes-wolf** [comment]
Watch out though, the mark size is in canvas, not plot-coordinates. When using with var-sized scatter plots you would need plot coordinate scaling (which could lead to stretched marks). Maybe add a flag if the scaling should be done?

**Comment by johannes-wolf** [comment]
Closed in favour of a different implementation.
