### ISSUE TITLE
Error importing the package on the web (failed to decompress package (invalid gzip header)

### ISSUE THREAD

**Issue by AdiWeit** [johannes-wolf/cetz#303]
I think I changed nothing, but now it shows the error message "failed to decompress package (invalid gzip header)" when trying to import the package. I am of course importing the package via `#import "@local/cetz:0.1.2"`.

**Comment by johannes-wolf** [comment]
This is nothing I can do anything about. Maybe repost the issue at https://github.com/typst/packages, hosting is done by the Typst project.
