### ISSUE TITLE
Wasted space in column chart

### ISSUE THREAD

**Issue by TabulateJarl8** [johannes-wolf/cetz#341]
Hey! I'm not sure if this is fixed in your latest unmerged PR which seems to modify how charts work, but I noticed that there is wasted space in column charts. I believe I am unable to adjust the spacing  in between the columns, and cetz is placing them too far away from the y-axis for my liking. Here's an example of the behavior I'm getting from cetz:

```typst
columnchart(
    mode: "clustered",
    size: (15, 7),
    bar-width: 0.4,
    value-key: (1,2,3),
    y-label: "Average Run Time (seconds)",
    y-tick-step: 5,
    (("Sorting List", 2.32, 2.88, 2.35), ("Intensive Calculation", 9.88, 13.60, 26.88), ("Factorials 1-4000", 6, 11.22, 14.1),),
  )
```

![image](https://github.com/johannes-wolf/cetz/assets/58576759/5690abd8-5781-49e4-8d2c-c6829935c458)

I would like to be able to adjust the space between/position the clusters on the x axis, as I can't make the graph any smaller without my text overlapping. Here's a comparison in tikz of what I'm trying to have happen:

![image](https://github.com/johannes-wolf/cetz/assets/58576759/3ddad950-b6cd-415e-81fa-d92c1e76f1a4)

Thank you for any help you can provide!

**Comment by johannes-wolf** [comment]
With #337 you can set the axis limits (`x-min`, `x-max`) manually to achieve the requested behavior. With the current chart API there is no way to modify the behavior.
