### ISSUE TITLE
align second axis numbering to the right by default

### ISSUE THREAD

**Issue by dscso** [johannes-wolf/cetz#365]
When 2 y axis are used, the numberings of the axis is centered to the left instead align it to the right. I'd propose to change this as this is much more readable
<a href="https://github.com/johannes-wolf/cetz/blob/master/tests/plot/ref.png"><img width="149" alt="image" src="https://github.com/johannes-wolf/cetz/assets/6866008/3c7967c1-ef95-4718-807f-d7615593ae2c">
</a>
If you agree, I'd work on a PR

**Comment by johannes-wolf** [comment]
I am fine with changing this, if it can be changed back to left alignment via a style option.

**Comment by johannes-wolf** [comment]
Are you still interested in implementing this? Otherwise I will close the issue.

**Comment by dscso** [comment]
I have found a workaround for my specific use case. If I implement it on another occasion, I will provide a PR
