### ISSUE TITLE
Allow Nested Element/Anchor Access

### ISSUE THREAD

**Issue by johannes-wolf** [johannes-wolf/cetz#382]
Allow accessing nested element anchors by registering elements insides groups via the element path.

Proposed syntax is to separate element names by slashes (like file-system paths):
```typst
group(name: "parent", {
  circle((), name: "child")
})

content("parent/child.center", [Example])
```

**Comment by fenjalien** [comment]
Is the slash actually necessary? With anchors now being functions, the group parent would receive `"child.center"` which would be identified as a child's anchor. If a default anchor is given (`"child"`), they could just override/take precedence over the group's anchors?

**Comment by johannes-wolf** [comment]
Without a slash, how should we know if `"elem.abc"` is `"elem.abc"` or `"elem.abc.default"`?
