### ISSUE TITLE
Strange artifacting in Firefox ESR when exporting to PDF

### ISSUE THREAD

**Issue by ThatOneCalculator** [johannes-wolf/cetz#394]
Here's what my code looks like in the editor, the graph looks fine:

![image](https://github.com/johannes-wolf/cetz/assets/44733677/cfe68304-170e-4146-bda0-ac8e15255d4c)

Now when exported to a PDF, it looks like this:

![image](https://github.com/johannes-wolf/cetz/assets/44733677/bea14c53-aec8-49a0-a54b-fdb6685b3d56)

```typst
#align(center)[#canvas(length: 0.4in, {
  // Function
  let f = x => 16 - x * x

  // Color transparency method
  let colTrans(color, transparency) = {
    return rgb(color.to-hex() + transparency);
  }
  
  // Left-hand Riemann sum method
  let riemann(transparency) = {
    let barColor = color.green
    let fixedOffset = 10/3 // Because plot has range [-20, 16]
    for i in (0, 1, 2, 3, 4, 5) {
      let height = f(i)
      if (f(i) < 0) {
        barColor = color.red
      }
      draw.fill(colTrans(
        barColor.lighten(70%).darken(8%),
        transparency
      ))
      draw.rect(
        (i, fixedOffset),
        (i + 1, (height / 6) + fixedOffset),
        stroke: colTrans(barColor.darken(30%), "88") + 1.1pt
      )
   }
  }

  // Draw Riemann sum with semi-opaque background
  riemann("66")

  // Plot with function
  draw.stroke(rgb("#555d"))
  plot.plot(size: (6, 6),
    x-grid: true,
    y-grid: true,
    axis-style: "school-book",
    x-tick-step: 1,
    y-tick-step: 4,
    padding: 10pt,
    {
      plot.add(
        domain: (0, 6),
        x => f(x),
        style: (
          stroke: blue + 1.5pt,
        ),
      )
    }
  )

  // Draw Riemann sum with transparent background (for lines over axes)
  riemann("00")
})]
```

Edit: this only seems to happen with Firefox's PDF viewer :thinking: 

Left is Firefox, right is GNOME Document Viewer (top) and Zathura mupdf (bottom)

![image](https://github.com/johannes-wolf/cetz/assets/44733677/d6900f74-517c-4609-8f0c-112e27b7e800)

**Comment by ThatOneCalculator** [comment]
Actually, this seems to be localized to Firefox ESR/Floorp. Left is Floorp (based on Firefox ESR), right is current Firefox.

![image](https://github.com/johannes-wolf/cetz/assets/44733677/06ff3499-49b2-4ede-899a-e901fdd3255b)

**Comment by ThatOneCalculator** [comment]
Closing as non-issue due to Firefox likely fixing this internally

**Comment by ThatOneCalculator** [comment]
Duplicate of https://github.com/typst/typst/issues/1611

**Comment by fenjalien** [comment]
Also duplicate of #163 (no worries :))
