### ISSUE TITLE
Draw right angles

### ISSUE THREAD

**Issue by avonmoll** [johannes-wolf/cetz#414]
I was looking for an easy way to draw right angles and couldn't find a built-in solution in CeTZ, so I wrote the following:

```
let angle-point-to-point(a, b) = {
    return calc.atan2(b.at(0) - a.at(0), b.at(1) - a.at(1))
  }
  
  let right-angle(origin, a, b, radius: 5pt, ..style) = {
    get-ctx(ctx => {
      let a = cetz.coordinate.resolve(ctx, a)
      let b = cetz.coordinate.resolve(ctx, b)
      let angle-a = angle-point-to-point(origin, a)
      let angle-b = angle-point-to-point(origin, b)
      line((origin, radius, a), (rel: (angle-b, radius)), ..style)
      line((origin, radius, b), (rel: (angle-a, radius)), ..style)
    })
  }
```

And used it like this: `right-angle(O, A, B, radius: 10pt, stroke: green)` to produce:
![image](https://github.com/johannes-wolf/cetz/assets/4260850/fe98a919-8efe-469a-b4ed-e1946fb8b05b)

It seems to work OK but I was wondering if drawing right angles can or will be built into CeTZ.

**Comment by johannes-wolf** [comment]
It should be built into the `angle` function, I think :+1:.
