### ISSUE TITLE
Marks in 3D

### ISSUE THREAD

**Issue by Sandybunting** [johannes-wolf/cetz#424]
Marks seem to work fairly well in 2D, but in trying to depict some 3D unit vectors I found that as soon as you add the Z coordinate, things get messy. I'm working with the 0.1.2 stable version, so apologies is this bug has already been fixed in the development version.
```
#import "@preview/cetz:0.1.2"
#cetz.canvas({
  import cetz.draw: *
  let origin = (0,0,0)
  // These work:
  line(origin,(1,0,0), mark: (end: ">"))
  line(origin,(0,1,0), mark: (end: ">"))

  // This doesn't work:
  line(origin,(0,0,1), mark: (end: ">"))

  // Even though this produces exactly the outcome that the previous line should:
  // line(origin,(1,1,0), mark: (end: ">"))

  // And this *really* doesn't work
  line(origin,(1,0.2,1), mark: (end: ">"))
})
```

**Comment by johannes-wolf** [comment]
On the mark PR for 0.2.0 it looks like this:
![Bildschirmfoto vom 2023-12-27 15-16-17](https://github.com/johannes-wolf/cetz/assets/519002/4f9ffc02-2fa1-4370-aa00-d115f2b373b9)
Is this what you would expect? You can set a `z-up` vector for marks to control their rotation.

**Comment by Sandybunting** [comment]
Yes, that looks right. For context, on 0.1.2, with the code I included above, it looks like this:
<img width="471" alt="Screenshot 2023-12-28 at 09 20 59" src="https://github.com/johannes-wolf/cetz/assets/42874530/920c2f54-b7a1-4c31-b502-d5fbdc366bff">

So some part of the mark PR must have fixed it already. Thanks for having a look. Cool package!
