### ISSUE TITLE
Bug: `point-on-path()`'s `<=` assertion might fail due to floating point imprecision

### ISSUE THREAD

**Issue by Leedehai** [johannes-wolf/cetz#431]
Hi - I found a curious error:
```
error: assertion failed: Absolute distance must be in path range, is: 3.1415158663623934
    ┌─ cetz/0.2.0/src/path-util.typ:162:10
    │  
162 │       assert(0 <= t and t <= length(segments),
    │ ╭───────────^
163 │ │       message: "Absolute distance must be in path range, is: " + repr(t))
```

After I went onto path-util.typ and modify the assertion message to let it print `length(segments)` value, it turns out to be
```
error: assertion failed: Absolute distance must be in path range, is: 3.1415158663623934 <= 3.141515866362393
    ┌─ cetz/0.2.0/src/path-util.typ:162:10
    │  
162 │       assert(0 <= t and t <= length(segments),
    │ ╭───────────^
163 │ │       message: "Absolute distance must be in path range, is: " + repr(t) + " <= " + str(length(segments)))
```

When the value `t` almost equals `length(segments)`, the `<=` comparison may fail due to numeric imprecision when handling floating point arithmetics.

This assertion was introduced to the `0.2.0` branch by https://github.com/johannes-wolf/cetz/pull/350.

**Comment by Leedehai** [comment]
Minimal code to trigger this bug:
```typ
// Use CeTZ 0.2.0
#cetz.canvas(length: 1cm, {
  import cetz.draw: arc-through
  import cetz.decorations: wave
  wave(arc-through((0,0), (1,1), (2,0)), N: 10) // N=10 triggers this error
})
```
Error (with my modification to print the `length(segments)` value): 
```
error: assertion failed: Absolute distance must be in path range, is: 3.1415158663623934 <= 3.141515866362393
    ┌─ cetz/0.2.0/src/path-util.typ:162:10
    │  
162 │       assert(0 <= t and t <= length(segments),
    │ ╭───────────^
163 │ │       message: "Absolute distance must be in path range, is: " + repr(t) + " <= " + repr(length(segments)))
```

In the sample code, if `N` is changed to `11` or `20`, the error persists. However, if `N` is `9`,`12`,`19`, `21`, the error disappears.

**Comment by Leedehai** [comment]
Maybe we could change the assertion to `0 <= t and t <= length(segments) * 1.0001` instead. The lower bound `0` is precise, because floating point arithmetics should not change the sign, but the upper bound needs a bit fuzziness to tolerate imprecision?

A more thorough discussion could be https://floating-point-gui.de/errors/comparison/

**Comment by johannes-wolf** [comment]
I am pro clamping the value to [0, distance].

**Comment by Leedehai** [comment]
Thanks! I was using the `spring-lib` branch, so naturally it doesn't contain #416, which does appear to have fixed the floating point equality comparison issue while improving the marks.

**Comment by Leedehai** [comment]
Thanks! I was using the `spring-lib` branch, so naturally it doesn't contain #416, which does appear to have fixed the floating point equality comparison issue (by deleting that assertion) while improving the marks.
