### ISSUE TITLE
[Feature Request] Center Arc function

### ISSUE THREAD

**Issue by isaacew** [johannes-wolf/cetz#437]
It would be less confusion if the arc command allowed for an additional parameter that made the arc command accept the syntax of center coordinate, starting angle, and stop angle. The current usage of starting point, start, and stop can be confusing for new users and having a different option will increase usability. 

An example would be 

`Let O =(0,0)
arc(center: O, start: 0deg, stop: 45deg, radius: 2)`

To do this same arc as currently available would be 

`arc(vector.add(O,(2,0)), start: 0deg, stop:45deg, radius: 2)`

In fact, it would be nice to update the current usage to be 

`arc(point: vector.add(O,(2,0)), start: 0deg, stop:45deg, radius: 2)`

This would improve the experiment as authors would know they are doing a point-starting arc, as is currently implemented. It would also allow for the suggested feature to be added and allow for future arc types in the future such as tangent arcs to elements. But, that's an issue for a later date and not the focus of this request.

**Comment by fenjalien** [comment]
In 0.2, (not sure about 0.1.2). You can use the "arc-center" anchor with the `anchor` argument. This will do the same thing as you propose.

 Arcs, by default start, from `start` to: aid in chaining multiple paths together (using the previous coordinate) and to be equivalent to tikz's arc path.
