### ISSUE TITLE
Bing Bong your rtl text handling is wrong

### ISSUE THREAD

**Issue by emilyyyylime** [johannes-wolf/cetz#455]
![Image of low quality tweet header as appears in "you've been hit by / you've been struck by / truck" meme](https://github.com/johannes-wolf/cetz/assets/40892795/e64edbb3-a2e6-4ada-8288-007f8dbd4340)
_You've been hit by-
You've been struck by-_
**RTL DOCUMENTS**

![Image of the triplet of the 'Nobody expects the Spanish inquisition' meme. Sorry I don't know the source](https://github.com/johannes-wolf/cetz/assets/40892795/514c8dae-4bac-4078-bd20-3a5dca9fb515)
**NOBODY EXPECTS** Right-To-Left documents

I can continue all day  
But I probably shouldn't

```typ
#import "@preview/cetz:0.1.2": canvas, draw

#set text(dir: ltr)
#canvas({
  import draw: *
  circle((0,0), radius: 1)
  line((0,0), (180deg, 1))
})

#set text(dir: rtl)
#canvas({
  import draw: *
  circle((0,0), radius: 1)
  line((0,0), (180deg, 1))
})
```

![Rendered using Typst-Renderer on the official Typst Discord server; https://discord.com/channels/1054443721975922748/1056574658771681361/1196709166778175628](https://github.com/johannes-wolf/cetz/assets/40892795/b571d0b0-ae6e-4a4c-b87f-82943d14d04f)

This at first looks intended but indeed it makes no sense, as both should be 180 degrees from the positive X axis. Additionally, in right-to-left documents, 0deg appears the exact same as above, so indeed polar points are very much Broken™

**Comment by johannes-wolf** [comment]
There is currently no way to query Typst for the text direction, so this can not yet get fixed.

**Comment by fenjalien** [comment]
> The `canvas` function could call `set text(direction: ltr)`

That would effect any content elements though. I would suggest using `scale((x: -1))` but it seems to not work in this case...

**Comment by emilyyyylime** [comment]
> There is currently no way to query Typst for the text direction, so this can not yet get fixed. The `canvas` function could call `set text(direction: ltr)`, maybe that is an option for now?

I don't quite know how the library works, perhaps there's an inappropriate use of `start` or `end` somewhere, or one of plenty of other constructs that could be rewritten in a more 'absolute' sense; but in the case that there truly is no better solution, I would prefer an automatic `set text(dir: ltr)`. If CeTZ itself isn't working, I sure won't be putting any content inside of it, so we should at the very least get CeTZ working.

**Comment by johannes-wolf** [comment]
As long as Typst does not allow getting the value of set-rules, we should force `ltr` direction (if there is no better solution available). The user can use `rtl` direction insides the `content(..)` calls.

**Comment by johannes-wolf** [comment]
Should be fixed with the linked PR.
