### ISSUE TITLE
Data lines clip into axes in plot

### ISSUE THREAD

**Issue by BattleCh1cken** [johannes-wolf/cetz#457]
- Cetz version: 0.2.0
- Typst version: 0.10.0

When using the plot function the data lines overlap the axis lines, creating a somewhat unclean look.

Here's an example of what that might look like:

![image](https://github.com/johannes-wolf/cetz/assets/75806385/6f45c687-f9b3-49cd-9271-53f64fc38bfe)

And here's the code to produce this:
```typ
#cetz.canvas({
  import cetz.plot
  plot.plot(
    size: (9,5),
    {
      plot.add(((1,2), (2,5), (3,5)))
      plot.add(((1,1), (2,8), (3,1)))
    }
  )
})

```

**Comment by johannes-wolf** [comment]
Will be implemented with #328.
