### ISSUE TITLE
Shorthands for the new anchors

### ISSUE THREAD

**Issue by fenjalien** [johannes-wolf/cetz#466]
The new path and border anchors don't have shorthands, you have to use them in dictionary form. It would be better if they hand shorthands like the named anchors.

We could use the exact same shortcut as named anchors, allow them as dot separated strings. However this may get tricky if a float is used for a path anchor, or an integer is used with intersections. Another option might be allowing them as a tuple in the form `(name, anchor)` although this may conflict with some already existing coordinates.

**Comment by johannes-wolf** [comment]
Maybe separate element name and anchor value by `@`? So it would be `"element@10%"`.
