### ISSUE TITLE
Option to use old "top,bottom,left,right" anchor border keys

### ISSUE THREAD

**Issue by JeyRunner** [johannes-wolf/cetz#474]
I think this is personal preference, but I guess it would be nice to have the option to set the anchor border key descriptors to the old style of "top, top-right, right, bottom, ..." instead of "north, north-est, ...".
Maybe also enable both at the same time if desired?

This could be an option of canvas or maybe a global option like:
```rust
set-border-anchor-key-style("compass")
set-border-anchor-key-style("vertical-horizontal") // for top, right, ...
set-border-anchor-key-style(("compass", "vertical-horizontal")  // both
``

**Comment by johannes-wolf** [comment]
We could support the old anchor names as aliases, but I am not sure if that is a good idea. How would elements that provide the alias names as anchors work? Should we then forbid all anchor names that are aliases? E.g. "left" translates to "west". `anchor("left", ...)` panics with a message saying that anchors must not use the name of an alias? I am not really sure…

**Comment by fenjalien** [comment]
I would rather not have to support aliases like these unless there is a significant want for it. As a workaround why not assign the strings to variables?
```
top = "north"
right = "east"
...
```

Supporting these aliases would also cause further confusion with #383

**Comment by JeyRunner** [comment]
I mean https://github.com/johannes-wolf/cetz/issues/383 is kind of the same thing.
Instead of top, above as an alias would also be fine (same for bottom/below).
But it would be nice to have these aliases for all directions (left, top-left or above-left).

I think supporting the old anchor names via aliases is a good solution. Also not allowing alias names for new defined anchors makes sense.

The problem with the variables (https://github.com/johannes-wolf/cetz/issues/474#issuecomment-1898898822) is that the error message will not be helpful when using e.g. top on a path:
Something like
```
north is not in start, ....
``` 

That could be better handled with real aliases.

**Comment by johannes-wolf** [comment]
We decided against adding aliases. If you want to use the old anchor names, please use the approach suggested by @fenjalien.
