### ISSUE TITLE
Mirror plot ticks to x2 and y2 axes

### ISSUE THREAD

**Issue by OverHash** [johannes-wolf/cetz#528]
Currently, cetz does not provide functionality to display ticks on the x2 and y2 axes unless something is plotted against it.

This may be undesirable in cases where the author wants to allow readers to read from the x2 and y2 axes, but does not have anything to necessarily plot against it.

For example, in the following case:
```typ
#import "@preview/cetz:0.2.1"

#cetz.canvas({
  import cetz.draw: *
  import cetz.plot

  plot.plot(
    size: (7, 7),
    x-tick-step: 0.2,
    x2-tick-step: 0.2,
    y-tick-step: 0.2,
    y2-tick-step: 0.2,
    x-label: "FPR",
    y-label: "TPR",
    x-min: 0,
    x-max: 1,
    y-equal: "x",
    {
      plot.add(((0, 0), (1.0, 1.0)), style: (stroke: (dash: "dashed")))
      // plot.add(domain: (0, 1.2), hypograph: true, (x) => { x })
    },
  )
})
```
will render as
![image](https://github.com/johannes-wolf/cetz/assets/46231745/f9583b3e-4294-4623-bba9-59452cd36d08)

while the desired output is something closer to
![image](https://github.com/johannes-wolf/cetz/assets/46231745/59d99818-f511-421c-9a40-1633929b9358)

Adding a feature to show tick labels on mirrored axes would be excellent for user experience, if `x2` or `y2` axes are not manually specified. It is okay if the user also has to specify the min/max range of these tick labels, but we should well document this in the manual.

**Comment by johannes-wolf** [comment]
With the linked PR you can set: `set-style(axes: (tick: (label: ("show": true))))` to force showing all tick labels, even for mirrored axes. The mirroring of tick lines also got fixed.
