### ISSUE TITLE
Viewbox i.e. ability to cut out a section/force a specific size for the canvas

### ISSUE THREAD

**Issue by ModProg** [johannes-wolf/cetz#82]
I want to add two views of the same graphic, one zoomed in.

Idealy, I'd like to reuse the cetz body, and just call `cetz.canvas` twice, specifying the section to show.

I think this could be done by having a `viewbox` argument that is `auto` by default, but can be set to either to a pair of coordinates like `rect` or, I could also see, having a struct like: `(pos: (center coordinates), size: (width, height))`.

**Comment by ModProg** [comment]
My workaround currently would be to do `box(clip: true, place(..., cetz.canvas(...)))`

**Comment by johannes-wolf** [comment]
Started working on a potential fix, maybe I'll get it working this week.

**Comment by johannes-wolf** [comment]
Closing this for now.
